---# COMPLETE CHARACTER FUNCTION PRACTICE USING DUAL---
--SELECT UPPER('oracle') FROM dual
--SELECT LOWER('ORACLE')FROM dual
--SELECT INITCAP('oracle sql programming')FROM dual
--SELECT LENGTH('oracle') FROM dual
--SELECT LENGTH('data science') FROM dual
--SELECT SUBSTR('oracle',1,3) FROM dual
--SELECT SUBSTR('oracle',2,3) FROM dual
--SELECT SUBSTR('oracle',3) FROM dual
--SELECT SUBSTR('oracle',-3)FROM dual
--SELECT CONCAT('oracle','programming') FROM dual
--SELECT CONCAT('oracle ','programming')FROM dual
--SELECT REPLACE('hello world','world','oracle') FROM dual
--SELECT REPLACE('123-456-789','-','') FROM dual
--SELECT TRIM('   oracle   ')FROM dual
--SELECT LTRIM('   oracle') FROM dual
--SELECT RTRIM('oracle   ') FROM dual
--SELECT LTRIM('****oracle','*')FROM dual
--SELECT RTRIM('1230000','0')FROM dual
--SELECT LPAD('123',5,'0')FROM dual
--SELECT LPAD('oracle',7,'_')FROM dual
--SELECT RPAD('123',5,'0')FROM dual
--SELECT RPAD('oracle',10,'*')FROM dual
--SELECT ASCII('A')FROM dual
--SELECT CHR(65)FROM dual
       ---# COMPLETE CHARACTER FUNCTION PRACTICE USING HR.EMPLOYEES---
--SELECT first_name, UPPER(first_name) FROM hr.employees;
--SELECT first_name, LOWER(first_name) FROM hr.employees;
--SELECT first_name,INITCAP(first_name)FROM hr.employees;
--SELECT first_name,LENGTH(first_name)FROM hr.employees;
--SELECT first_name,SUBSTR(first_name,1,3) FROM hr.employees;
-- SELECT first_name, SUBSTR(first_name,1,1)FROM hr.employees;
--SELECT first_name,SUBSTR(first_name,-3)FROM hr.employees;
--SELECT first_name,SUBSTR(first_name,1,1)FROM hr.employees;
--SELECT first_name,SUBSTR(first_name,-3)FROM hr.employees;
--SELECT first_name,last_name,CONCAT(first_name,last_name)FROM hr.employees;
--SELECT first_name || ' ' || last_name AS full_name FROM hr.employees;
--SELECT first_name,REPLACE(first_name,'a','@')FROM hr.employees;
--SELECT first_name,TRIM(first_name) FROM hr.employees;
--SELECT first_name,LTRIM(first_name)FROM hr.employees;
-- SELECT first_name,RTRIM(first_name)FROM hr.employees;
-- SELECT employee_id,LPAD(employee_id,6,'0')FROM hr.employees;
--SELECT first_name, RPAD(first_name,15,'.')FROM hr.employees;
--SELECT first_name,ASCII(first_name)FROM hr.employees;


-------# COMPLETE NUMERIC FUNCTION PRACTICE USING DUAL-----
-- SELECT CEIL(10.1)FROM dual;
--SELECT CEIL(10.9) FROM dual;
--SELECT FLOOR(10.1)FROM dual;
--SELECT FLOOR(10.9)FROM dual;
--SELECT MOD(10,3)FROM dual;
--SELECT MOD(20,5)FROM dual;
--SELECT ABS(-10.3)FROM dual;
--SELECT ABS(-100)FROM dual;
-- SELECT POWER(2,0.5)FROM dual;
--SELECT POWER(2,1/2) FROM dual;
--SELECT SQRT(2)FROM dual;
--SELECT SQRT(16) FROM dual;


-----## Character Functions-----
--SELECT UPPER('data engineering') FROM dual;
--SELECT LOWER('DATA ENGINEERING') FROM dual;
--SELECT INITCAP('oracle database administrator') FROM dual;
--SELECT LENGTH('machine learning') FROM dual;
--SELECT SUBSTR('artificial intelligence',1,10) FROM dual;
--SELECT CONCAT('Oracle ','SQL') FROM dual;
--SELECT REPLACE('hello python','python','oracle') FROM dual;
--SELECT TRIM('    database    ') FROM dual;
--SELECT LTRIM('00000500','0') FROM dual;
--SELECT RTRIM('500000','0') FROM dual;
--SELECT LPAD('500',8,'0') FROM dual;
--SELECT RPAD('SQL',10,'.') FROM dual;
--SELECT ASCII('A') FROM dual;
--SELECT CHR(65) FROM dual;


-----## Numeric Functions-----
--SELECT CEIL(25.01) FROM dual;
-- SELECT FLOOR(25.99) FROM dual;
--SELECT MOD(25,4) FROM dual;
--SELECT ABS(-999.50) FROM dual;
--SELECT POWER(3,4) FROM dual;
--SELECT SQRT(81) FROM dual;

-----## HR.EMPLOYEES Practice-----
--SELECT first_name,  UPPER(first_name)FROM hr.employees;
--SELECT first_name,LOWER(first_name)FROM hr.employees;
--SELECT first_name, INITCAP(first_name)FROM hr.employees;
--SELECT first_name,LENGTH(first_name)FROM hr.employees;
--SELECT first_name,SUBSTR(first_name,1,3)FROM hr.employees;
--SELECT first_name || ' ' || last_name AS full_name FROM hr.employees;
-- SELECT employee_id,LPAD(employee_id,6,'0') AS formatted_id FROM hr.employees;
--SELECT first_name, RPAD(first_name,20,'.') AS formatted_name FROM hr.employees;
--SELECT employee_id,salary,CEIL(salary / 12) AS ceil_monthly_salaryFROM hr.employees;
--SELECT employee_id,salary, FLOOR(salary / 12) AS floor_monthly_salary FROM hr.employees;
--SELECT employee_id,MOD(employee_id,2) AS remainderFROM hr.employees;
--SELECT employee_id, salary,ABS(salary - 10000) AS difference_from_10000 FROM hr.employees;
--SELECT employee_id,salary,POWER(salary,2) AS salary_square FROM hr.employees;
--SELECT employee_id, salary,SQRT(salary) AS salary_square_rootFROM hr.employees;